export const translations = {
  en: {
    sidebar: {
      recruiterDesk: "Recruiter Desk",
      positions:  "Positions",
      customers:  "Customers",
      candidates: "Candidates",
      linkedin:   "LinkedIn",
      gallery:    "Image Gallery",
      emailInbox: "Email Inbox",
      leads:      "Leads",
      settingsSection: "Settings",
      greetings: ["Good morning", "Good afternoon", "Good evening"],
      tagline:   "Connecting Talent.\nPowering Futures.",
    },
    positions: {
      title:       "Positions",
      eyebrow:     "Positions",
      newPosition: "+ New Position",
      subtitle: (o: number, f: number) =>
        `${o} open · ${f} filled`,
      metrics: {
        open:      "Open",
        filled:    "Filled",
        cancelled: "Cancelled",
        toReview:  "To Review",
      },
      statusLabel: {
        open:      "Open",
        filled:    "Filled",
        cancelled: "Cancelled",
      },
      emptyTitle:    "No positions yet",
      emptySubtitle: "Add your first open role to start building your candidate pipeline.",
      emptyCta:      "+ New Position",
      filteredEmpty: "No positions match this filter",
      clearFilter:   "Clear filter",
      searchPlaceholder: "Search by title or client…",
      noSearchResults:   "No positions match your search",
      clearSearch:       "Clear search",
      noCandidates:      "No candidates",
      matched:           "matched",
      newCandidate:      "new candidate",
      newCandidates:     "new candidates",
      pipeline: {
        inPool:       "In Pool",
        clientReview: "Client Review",
        interview:    "Interview",
        hired:        "Hired",
      },
    },
    detail: {
      back:         "← All Positions",
      location:     "Location",
      salary:       "Salary",
      created:      "Created",
      addLocation:  "Add location",
      addSalary:    "Add salary range",
      today:        "Today",
      yesterday:    "Yesterday",
      daysAgo: (n: number) => `${n} days ago`,
      polishWithAI:      "✨ Polish",
      polishing:         "Polishing…",
      publishJob:        "Publish Job",
      inPool: (n: number) => `${n} candidate${n !== 1 ? "s" : ""} in pool`,
      statusLabel: {
        open:      "Open",
        filled:    "Filled",
        cancelled: "Cancelled",
      },
      aboutJob:        "About the job",
      addDescription:  "+ Add job description",
      requirements:    "Requirements",
      addRequirements: "+ Add requirements",
      edit:   "✏ Edit",
      save:   "Save",
      cancel: "Cancel",
      candidates:      "Candidates",
      matched:         "matched",
      noCandidatesYet: "No candidates matched yet",
      showWeak: (n: number) => `▼ Show ${n} weak match${n !== 1 ? "es" : ""}`,
      hideWeak: (n: number) => `▲ Hide ${n} weak match${n !== 1 ? "es" : ""}`,
      rejected: (n: number) => `${n} candidate${n !== 1 ? "s" : ""} rejected`,
      moveToStage: "Move to stage",
      reject:      "Reject",
      pendingSection:      "To Review",
      reviewedSection:    "Relevant",
      notRelevantSection: "Not Relevant",
      markRelevant:    "Relevant",
      markNotRelevant: "Not Relevant",
      showNotRelevant: (n: number) => `▼ Show ${n} not relevant`,
      hideNotRelevant: (n: number) => `▲ Hide ${n} not relevant`,
      candidateStatus: {
        open:          "In Pool",
        client_review: "Client Review",
        interview:     "Interview",
        hired:         "Hired",
        rejected:      "Rejected",
        relevant:      "Relevant",
        not_relevant:  "Not Relevant",
      },
      strengthLabel: {
        strong:   "Strong Match",
        possible: "Possible Match",
        weak:     "Weak Match",
      },
      whyFit:       "Why they fit",
      copy:         "Copy",
      copied:       "Copied!",
      viewProfile:  "View full profile",
      experience:   "Experience",
      yrsExp: (n: number) => `${n} yr${n !== 1 ? "s" : ""}`,
      skills:       "Skills",
      summary:      "Summary",
      contact:      "Contact",
      jobSourceLink:          "View job posting",
      removePositionOption:   "Remove position",
      removePositionTitle:    "Remove position?",
      removePositionBody:     (title: string) => `This will permanently delete "${title}" and all its candidate matches. This cannot be undone.`,
      removePositionConfirm:  "Yes, remove",
      postToLinkedin:         "Post to LinkedIn",
      postedToLinkedin:       "✓ Posted to LinkedIn",
      linkedinModal: {
        title:           "Post to LinkedIn",
        langHe:          "עברית",
        langEn:          "English",
        generating:      "Generating post…",
        shorten:         "Shorten",
        expand:          "Expand",
        noImages:        "No images yet — add some in Studio",
        imageOf:         (n: number, total: number) => `${n} / ${total}`,
        postBtn:         "Post to LinkedIn",
        posting:         "Posting…",
        markManual:      "Mark as posted manually",
        manualUrlLabel:  "LinkedIn post URL (optional)",
        manualConfirm:   "Confirm",
        cancel:          "Cancel",
        preview:         "Preview",
        attachImage:      "Attach image",
        removeAttachment: "Remove image",
        browseGallery:    "Browse gallery",
        chooseImage:      "Choose image",
        errorNotConnected: "LinkedIn not connected — connect first in Settings",
      },
      sendToClient:  "Send to Client",
      emailDraft: {
        title:              "Email to Client",
        drafting:           "Drafting email…",
        to:                 "To",
        toPlaceholder:      "Client email address",
        subject:            "Subject",
        body:               "Message",
        includeContact:     "Include candidate contact info",
        contactHeader:      "Candidate contact details",
        contactEmailLabel:  "Email",
        contactPhoneLabel:  "Phone",
        cvNote:             (filename: string) => `Remember to attach the CV in Outlook: ${filename}`,
        cvNoteNoFile:       "Remember to attach the candidate's CV in Outlook",
        openOutlook:        "Open in Outlook",
        cancel:             "Cancel",
        draftError:         "Could not draft email — try again",
      },
      appliedBadge: "Applied for this role",
      poolBadge:    "Pool",
    },
    candidates: {
      title:          "Candidates",
      searchPlaceholder: "Search by name, skill, title, location…",
      uploadBtn:      "Upload CV",
      dropzone:       "Drop CVs here or click to upload",
      dropzoneSub:    "PDF or Word · one or many at once",
      processing:     "Processing…",
      parsed:         "Parsed",
      matched: (n: number) => `Matched to ${n} position${n !== 1 ? "s" : ""}`,
      failedParse:    "Could not parse",
      alreadyExists:  "Already in pool",
      emptyTitle:     "No candidates yet",
      emptySubtitle:  "Upload CVs to build your talent pool. The system will match them to open positions automatically.",
      noResults:      "No candidates match your search",
      clearSearch:    "Clear search",
      sourceLabels:   { jobmaster: "JobMaster", manual: "Manual", website: "Website" } as Record<string, string>,
      yrsExp: (n: number) => `${n} yr${n !== 1 ? "s" : ""}`,
      back:           "← All Candidates",
      contact:        "Contact",
      experience:     "Experience",
      skills:         "Skills",
      industries:     "Industries",
      summary:        "Summary",
      matchedRoles:   "Matched Roles",
      noMatches:      "No position matches yet",
      downloadCV:     "Download CV",
      updatedAt:      "Last updated",
    },
    emailInbox: {
      title:                "Email Inbox",
      subtitle:             "Connected to the Gmail CV inbox — auto-polled every 15 minutes. CVs are linked to positions and matched automatically.",
      checking:             "Checking connection…",
      connected:            "Connected to Gmail",
      connectFirst:         "Save Gmail credentials above before polling.",
      settingsTitle:        "Gmail IMAP Settings",
      labelEmail:           "Gmail address",
      labelAppPassword:     "App Password",
      appPasswordPlaceholder: "xxxx xxxx xxxx xxxx",
      appPasswordHint:      "Generate an App Password in Google Account → Security → 2-Step Verification.",
      saveBtn:              "Save",
      saving:               "Saving…",
      cancel:               "Cancel",
      changeSettings:       "Change settings",
      pollTitle:            "Poll Inbox",
      pollBtn:              "Poll Now",
      polling:              "Polling…",
      resultScanned:        (n: number) => `${n} email${n !== 1 ? "s" : ""} scanned`,
      resultImported:       (n: number) => `${n} CV${n !== 1 ? "s" : ""} imported`,
      resultErrors:         "Errors:",
      lastPolled:           "Last polled:",
      never:                "Never",
      appliedBadge:         "Applicant",
      autoSyncActive:       "Auto-sync active",
      autoSyncInterval:     "Scans inbox every 15 minutes",
      autoSyncNext:         (n: number) => `Next scan in ${n} min`,
      autoSyncSoon:         "Scanning soon…",
      updateTitle:          "App Update",
      updateVersion:        "Version",
      updateCommit:         "Build",
      updateLastUpdated:    "Last updated",
      updateBtn:            "Update Now",
      updating:             "Starting update…",
      updateStarted:        "Update started — the app will restart in ~2 minutes. Reopen the page after that.",
      updateError:          "Failed to start update",
    },
    customers: {
      title:         "Customers",
      addClient:     "+ Add Client",
      totalClients:  "Total Clients",
      active:        "Active",
      totalContacts: "Total Contacts",
      openPositions: "Open Positions",
      contacts:      "Contacts",
      addContact:    "+ Add Contact",
      emptyTitle:    "No clients yet",
      emptySubtitle: "Add your first client to start building your customer directory.",
      emptyCta:      "+ Add Client",
      back:          "← All Customers",
      edit:          "✏ Edit",
      save:          "Save",
      cancel:        "Cancel",
      industry:      "Industry",
      website:       "Website",
      linkedin:      "LinkedIn",
      noPositions:   "No open positions linked to this client.",
      noContacts:    "No contacts yet.",
      deleteContact:  "Remove",
      confirmDelete:  "Remove this contact?",
      candidateCount: (n: number) => `${n} candidate${n !== 1 ? "s" : ""}`,
      removeClientOption:  "Remove client",
      removeClientTitle:   "Remove client?",
      removeClientBody:    (name: string) => `This will permanently delete "${name}" and all associated data. This cannot be undone.`,
      removeClientConfirm: "Yes, remove",
      // Add Client modal
      addClientTitle:         "Add Client",
      step1Title:             "LinkedIn Company URL",
      linkedinUrlLabel:       "LinkedIn Company URL",
      linkedinUrlPlaceholder: "https://www.linkedin.com/company/…",
      fetchBtn:               "Fetch",
      fetching:               "Fetching…",
      fetchError:             "Couldn't fetch company data. Check the URL and try again.",
      fillManually:           "Fill in manually",
      step2Title:             "Review & Save",
      companyName:            "Company Name",
      tagline:                "Tagline",
      saveClient:             "Save Client",
      saving:                 "Saving…",
      // Add Contact modal
      addContactTitle: "Add Contact",
      contactName:     "Name",
      contactTitle:    "Title",
      contactEmail:    "Email",
      contactPhone:    "Phone",
      saveContact:     "Save Contact",
      // Position modal dropdown
      clientDropdownPlaceholder: "Search clients…",
      createNewClient:           "+ Create new client",
    },
    linkedin: {
      title:            "LinkedIn Studio",
      checking:         "Checking connection…",
      connected:        "Connected",
      connectedAs:      "Connected as",
      notConnected:     "Not connected",
      connectBtn:       "Connect LinkedIn",
      // Composer
      composer:         "Post Composer",
      typeJob:          "Job Post",
      typeHoliday:      "Holiday",
      typePR:           "Company Update",
      hintPlaceholder:  "Optional hint — role name, holiday, topic…",
      generateBtn:      "Generate with AI",
      generating:       "Generating…",
      textareaPlaceholder: "Your post will appear here. Edit freely.",
      shorten:          "Shorten",
      expand:           "Expand",
      selectImage:      "Image",
      attachImage:      "Attach image",
      postBtn:          "Post to LinkedIn",
      posting:          "Posting…",
      preview:          "Preview",
      postSuccess:      "Posted successfully!",
      viewPost:         "View post →",
      notConnectedHint: "Connect LinkedIn above to enable posting",
      errorGenerate:    "Generation failed — try again",
      errorPost:        "Posting failed — try again",
      // Gallery
      imageGallery:     "Image Gallery",
      uploadBtn:        "Upload Images",
      uploading:        "Uploading…",
      dropHere:         "Drop images here or click Upload",
      noImagesTitle:    "No images yet",
      noImagesBody:     "Upload images to use them in your LinkedIn posts.",
      removeImage:      "Remove",
      selected:         "Selected",
      errorUpload:      "Upload failed — try again",
      createWithAI:     "Create with AI",
      createWithAIHint: "Generate a branded image with AI",
      removeSelected:   (n: number) => `${n} image${n !== 1 ? "s" : ""} selected`,
      clearSelection:   "Clear",
      generateModal: {
        title:              "Create an Image with AI",
        promptTitle:        "Review the Prompt",
        brandingNote:       "Focus Group branding guidelines are already applied",
        typeLabel:          "Type",
        typeImage:          "Photo",
        typePoster:         "Poster",
        promptLabel:        "Describe the image you want",
        promptPlaceholderImage:  "e.g. A professional team in a modern office…",
        promptPlaceholderPoster: "e.g. 33 years of recruiting excellence",
        colorLabel:         "Style",
        colorFull:          "Color",
        colorMono:          "Black & White",
        langLabel:          "Text in image",
        langHe:             "Hebrew",
        langEn:             "English",
        generateBtn:        "✦ Create Image",
        generating:         "Creating…",
        previewTitle:       "Preview",
        backBtn:            "← Back",
        saveBtn:            "Save to Gallery",
        saving:             "Saving…",
        approxCost:         "Approx. cost",
        errorGenerate:      "Image creation failed — try again",
        errorSave:          "Save failed — try again",
      },
    },
    leads: {
      title:               "Leads",
      tabLeads:            "Leads",
      tabTemplates:        "Comment Templates",
      searchPlaceholder:   "Search by name, company, headline…",
      noLeads:             "No leads yet",
      noLeadsHint:         "Use the LinkedIn extension to comment on posts — leads will appear here automatically.",
      noResults:           "No leads match your search",
      clearSearch:         "Clear search",
      notesPlaceholder:    "Add a note…",
      saveNotes:           "Save",
      deleteLead:          "Remove",
      confirmDelete:       "Remove this lead?",
      viewProfile:         "View on LinkedIn",
      usedTemplate:        "Template used",
      addedOn:             "Added",
      noTemplates:         "No templates yet",
      noTemplatesHint:     "Add your first comment template below.",
      newTemplate:         "+ New Template",
      templateTitle:       "Template name",
      templateTitlePlaceholder: "e.g. General opening",
      templateBody:        "Comment text",
      templateBodyPlaceholder:  "Write the comment Jacob will paste…",
      templateImage:       "Image (optional)",
      chooseImage:         "Choose from gallery",
      noImageSelected:     "No image",
      removeImage:         "Remove",
      saveTemplate:        "Save Template",
      saving:              "Saving…",
      cancel:              "Cancel",
      editTemplate:        "Edit",
      deleteTemplate:      "Delete",
      confirmDeleteTemplate: "Delete this template?",
    },
    modal: {
      newPosition:  "New Position",
      howToAdd:     "How would you like to add it?",
      pasteEmail:   "Paste the job email",
      reviewSave:   "Review & Save",
      pasteTitle:   "Paste from email",
      pasteSub:     "Copy & paste a job email — we'll fill in the fields automatically",
      manualTitle:  "Fill in manually",
      manualSub:    "Type in the job details yourself",
      emailPlaceholder: "Paste the full email here — subject, body, anything you have. The more detail, the better.",
      parseError:   "Couldn't read the email. Try again or fill in the fields manually.",
      back:         "← Back",
      skipManual:   "Skip, fill manually",
      extract:      "Extract details →",
      reading:      "Reading email…",
      jobTitle:     "Job Title",
      jobTitlePlaceholder: "Senior Software Engineer",
      client:       "Client",
      clientHint:   "Who are you recruiting for?",
      clientPlaceholder: "Acme Corp",
      location:     "Location",
      salaryRange:  "Salary Range",
      description:  "Job Description",
      descriptionPlaceholder: "Describe the role, responsibilities, company culture…",
      requirements: "Requirements",
      requirementsPlaceholder: "Skills, experience, qualifications needed…",
      requiredError: "Job title and client name are required.",
      saveError:    "Something went wrong. Please try again.",
      createPosition: "Create Position",
      saving:       "Saving…",
    },
  },

  he: {
    sidebar: {
      recruiterDesk: "מערכת גיוס",
      positions:  "משרות",
      customers:  "לקוחות",
      candidates: "מועמדים",
      linkedin:   "לינקדאין",
      gallery:    "גלריית תמונות",
      emailInbox: "תיבת דואר",
      leads:      "לידים",
      settingsSection: "הגדרות",
      greetings: ["בוקר טוב", "צהריים טובים", "ערב טוב"],
      tagline:   ".מגייסים את האדם הנכון\nבזמן הנכון.",
    },
    positions: {
      title:       "משרות",
      eyebrow:     "ניהול משרות",
      newPosition: "+ משרה חדשה",
      subtitle: (o: number, f: number) =>
        `${o} פתוחות · ${f} אוישו`,
      metrics: {
        open:      "פתוחות",
        filled:    "אוישו",
        cancelled: "בוטלו",
        toReview:  "מועמדים לסקירה",
      },
      statusLabel: {
        open:      "פתוחה",
        filled:    "אוישה",
        cancelled: "בוטלה",
      },
      emptyTitle:    "אין משרות עדיין",
      emptySubtitle: "הוסף את המשרה הראשונה שלך כדי להתחיל לבנות את צינור המועמדים.",
      emptyCta:      "+ משרה חדשה",
      filteredEmpty: "אין משרות התואמות לסינון זה",
      clearFilter:   "נקה סינון",
      searchPlaceholder: "חיפוש לפי תפקיד או לקוח…",
      noSearchResults:   "אין משרות התואמות לחיפוש",
      clearSearch:       "נקה חיפוש",
      noCandidates:      "אין מועמדים",
      matched:           "הותאמו",
      newCandidate:      "מועמד חדש",
      newCandidates:     "מועמדים חדשים",
      pipeline: {
        inPool:       "בסל",
        clientReview: "בדיקת לקוח",
        interview:    "ראיון",
        hired:        "גויס",
      },
    },
    detail: {
      back:        "כל המשרות →",
      location:    "מיקום",
      salary:      "שכר",
      created:     "נוצרה",
      addLocation: "הוסף מיקום",
      addSalary:   "הוסף טווח שכר",
      today:       "היום",
      yesterday:   "אתמול",
      daysAgo: (n: number) => `לפני ${n} ימים`,
      polishWithAI:      "✨ שיפור",
      polishing:         "משפר…",
      publishJob:        "פרסם משרה",
      inPool: (n: number) => `${n} מועמד${n !== 1 ? "ים" : ""} בסל`,
      statusLabel: {
        open:      "פתוחה",
        filled:    "אוישה",
        cancelled: "בוטלה",
      },
      aboutJob:        "אודות המשרה",
      addDescription:  "+ הוסף תיאור משרה",
      requirements:    "דרישות",
      addRequirements: "+ הוסף דרישות",
      edit:   "✏ עריכה",
      save:   "שמור",
      cancel: "ביטול",
      candidates:      "מועמדים",
      matched:         "הותאמו",
      noCandidatesYet: "לא הותאמו מועמדים עדיין",
      showWeak: (n: number) => `▼ הצג ${n} התאמה${n !== 1 ? "ות" : ""} חלשה`,
      hideWeak: (n: number) => `▲ הסתר ${n} התאמה${n !== 1 ? "ות" : ""} חלשה`,
      rejected: (n: number) => `${n} מועמד${n !== 1 ? "ים" : ""} נדחו`,
      moveToStage: "העבר לשלב",
      reject:      "דחה",
      pendingSection:      "לסקירה",
      reviewedSection:    "רלוונטי",
      notRelevantSection: "לא רלוונטי",
      markRelevant:    "רלוונטי",
      markNotRelevant: "לא רלוונטי",
      showNotRelevant: (n: number) => `▼ הצג ${n} לא רלוונטי${n !== 1 ? "ם" : ""}`,
      hideNotRelevant: (n: number) => `▲ הסתר ${n} לא רלוונטי${n !== 1 ? "ם" : ""}`,
      candidateStatus: {
        open:          "מאגר",
        client_review: "בדיקת לקוח",
        interview:     "ראיון",
        hired:         "גויס",
        rejected:      "נדחה",
        relevant:      "רלוונטי",
        not_relevant:  "לא רלוונטי",
      },
      strengthLabel: {
        strong:   "התאמה חזקה",
        possible: "התאמה אפשרית",
        weak:     "התאמה חלשה",
      },
      whyFit:       "למה הם מתאימים",
      copy:         "העתק",
      copied:       "הועתק!",
      viewProfile:  "לפרופיל המלא",
      experience:   "ניסיון",
      yrsExp: (n: number) => `${n} שנ${n !== 1 ? "ים" : "ה"}`,
      skills:       "כישורים",
      summary:      "סיכום",
      contact:      "פרטי קשר",
      jobSourceLink:          "צפה במשרה המקורית",
      removePositionOption:   "הסר משרה",
      removePositionTitle:    "הסר משרה?",
      removePositionBody:     (title: string) => `פעולה זו תמחק לצמיתות את "${title}" ואת כל התאמות המועמדים שלה. לא ניתן לבטל פעולה זו.`,
      removePositionConfirm:  "כן, הסר",
      postToLinkedin:         "פרסם בלינקדאין",
      postedToLinkedin:       "✓ פורסם בלינקדאין",
      linkedinModal: {
        title:           "פרסום בלינקדאין",
        langHe:          "עברית",
        langEn:          "English",
        generating:      "מייצר פוסט…",
        shorten:         "קצר",
        expand:          "הרחב",
        noImages:        "אין תמונות עדיין — הוסף ב-Studio",
        imageOf:         (n: number, total: number) => `${n} / ${total}`,
        postBtn:         "פרסם בלינקדאין",
        posting:         "מפרסם…",
        markManual:      "סמן כפורסם ידנית",
        manualUrlLabel:  "קישור לפוסט בלינקדאין (אופציונלי)",
        manualConfirm:   "אשר",
        cancel:          "ביטול",
        preview:         "תצוגה מקדימה",
        attachImage:      "צרף תמונה",
        removeAttachment: "הסר תמונה",
        browseGallery:    "בחר מהגלריה",
        chooseImage:      "בחר תמונה",
        errorNotConnected: "לינקדאין לא מחובר — חבר תחילה בהגדרות",
      },
      sendToClient:  "שלח ללקוח",
      emailDraft: {
        title:              "אימייל ללקוח",
        drafting:           "מנסח אימייל…",
        to:                 "אל",
        toPlaceholder:      "כתובת אימייל של הלקוח",
        subject:            "נושא",
        body:               "גוף",
        includeContact:     "כלול פרטי קשר של המועמד",
        contactHeader:      "פרטי קשר של המועמד",
        contactEmailLabel:  "אימייל",
        contactPhoneLabel:  "טלפון",
        cvNote:             (filename: string) => `זכור לצרף קורות חיים ב-Outlook: ${filename}`,
        cvNoteNoFile:       "זכור לצרף את קורות החיים של המועמד ב-Outlook",
        openOutlook:        "פתח ב-Outlook",
        cancel:             "ביטול",
        draftError:         "לא ניתן לנסח אימייל — נסה שנית",
      },
      appliedBadge: "הגיש מועמדות",
      poolBadge:    "מאגר",
    },
    customers: {
      title:         "לקוחות",
      addClient:     "+ הוסף לקוח",
      totalClients:  "סה\"כ לקוחות",
      active:        "פעילים",
      totalContacts: "סה\"כ אנשי קשר",
      openPositions: "משרות פתוחות",
      contacts:      "אנשי קשר",
      addContact:    "+ הוסף איש קשר",
      emptyTitle:    "אין לקוחות עדיין",
      emptySubtitle: "הוסף את הלקוח הראשון שלך כדי להתחיל לבנות את ספריית הלקוחות.",
      emptyCta:      "+ הוסף לקוח",
      back:          "כל הלקוחות →",
      edit:          "✏ עריכה",
      save:          "שמור",
      cancel:        "ביטול",
      industry:      "תעשייה",
      website:       "אתר",
      linkedin:      "לינקדאין",
      noPositions:   "אין משרות פתוחות המקושרות ללקוח זה.",
      noContacts:    "אין אנשי קשר עדיין.",
      deleteContact:  "הסר",
      confirmDelete:  "להסיר איש קשר זה?",
      candidateCount: (n: number) => `${n} מועמד${n !== 1 ? "ים" : ""}`,
      removeClientOption:  "הסר לקוח",
      removeClientTitle:   "הסר לקוח?",
      removeClientBody:    (name: string) => `פעולה זו תמחק לצמיתות את "${name}" וכל הנתונים הקשורים. לא ניתן לבטל פעולה זו.`,
      removeClientConfirm: "כן, הסר",
      addClientTitle:         "הוסף לקוח",
      step1Title:             "כתובת LinkedIn של החברה",
      linkedinUrlLabel:       "כתובת LinkedIn",
      linkedinUrlPlaceholder: "https://www.linkedin.com/company/…",
      fetchBtn:               "שלוף",
      fetching:               "שולף…",
      fetchError:             "לא הצלחנו לשלוף נתוני חברה. בדוק את הכתובת ונסה שוב.",
      fillManually:           "מלא ידנית",
      step2Title:             "סקירה ושמירה",
      companyName:            "שם החברה",
      tagline:                "תיאור קצר",
      saveClient:             "שמור לקוח",
      saving:                 "שומר…",
      addContactTitle: "הוסף איש קשר",
      contactName:     "שם",
      contactTitle:    "תפקיד",
      contactEmail:    "אימייל",
      contactPhone:    "טלפון",
      saveContact:     "שמור איש קשר",
      clientDropdownPlaceholder: "חפש לקוחות…",
      createNewClient:           "+ צור לקוח חדש",
    },
    linkedin: {
      title:            "סטודיו לינקדאין",
      checking:         "בודק חיבור…",
      connected:        "מחובר",
      connectedAs:      "מחובר בתור",
      notConnected:     "לא מחובר",
      connectBtn:       "חבר לינקדאין",
      // Composer
      composer:         "יצירת פוסט",
      typeJob:          "משרה",
      typeHoliday:      "חג",
      typePR:           "עדכון חברה",
      hintPlaceholder:  "רמז אופציונלי — שם תפקיד, חג, נושא…",
      generateBtn:      "צור עם AI",
      generating:       "מייצר…",
      textareaPlaceholder: "הפוסט יופיע כאן. ערוך בחופשיות.",
      shorten:          "קצר",
      expand:           "הרחב",
      selectImage:      "תמונה",
      attachImage:      "צרף תמונה",
      postBtn:          "פרסם בלינקדאין",
      posting:          "מפרסם…",
      preview:          "תצוגה מקדימה",
      postSuccess:      "פורסם בהצלחה!",
      viewPost:         "לצפייה בפוסט ←",
      notConnectedHint: "חבר לינקדאין למעלה כדי לאפשר פרסום",
      errorGenerate:    "היצירה נכשלה — נסה שוב",
      errorPost:        "הפרסום נכשל — נסה שוב",
      // Gallery
      imageGallery:     "גלריית תמונות",
      uploadBtn:        "העלה תמונות",
      uploading:        "מעלה…",
      dropHere:         "גרור תמונות לכאן או לחץ על העלאה",
      noImagesTitle:    "אין תמונות עדיין",
      noImagesBody:     "העלה תמונות לשימוש בפוסטים שלך בלינקדאין.",
      removeImage:      "הסר",
      selected:         "נבחרה",
      errorUpload:      "ההעלאה נכשלה — נסה שוב",
      createWithAI:     "צור עם AI",
      createWithAIHint: "יצירת תמונה ממותגת עם AI",
      removeSelected:   (n: number) => `${n} תמונ${n !== 1 ? "ות" : "ה"} נבחר${n !== 1 ? "ו" : "ה"}`,
      clearSelection:   "נקה",
      generateModal: {
        title:              "יצירת תמונה עם AI",
        promptTitle:        "בדוק את הפרומפט",
        brandingNote:       "הנחיות המיתוג של Focus Group כבר מוגדרות",
        typeLabel:          "סוג",
        typeImage:          "תמונה",
        typePoster:         "פוסטר",
        promptLabel:        "תאר את התמונה שברצונך ליצור",
        promptPlaceholderImage:  "לדוגמה: צוות מקצועי בחגיגת גיוס מוצלח, משרד מודרני…",
        promptPlaceholderPoster: "לדוגמה: 33 שנות מצוינות בגיוס מנהלים",
        colorLabel:         "סגנון",
        colorFull:          "צבעוני",
        colorMono:          "שחור-לבן",
        langLabel:          "טקסט בתמונה",
        langHe:             "עברית",
        langEn:             "אנגלית",
        generateBtn:        "✦ צור תמונה",
        generating:         "יוצר תמונה…",
        previewTitle:       "תצוגה מקדימה",
        backBtn:            "חזור ←",
        saveBtn:            "שמור לגלריה",
        saving:             "שומר…",
        approxCost:         "עלות משוערת",
        errorGenerate:      "יצירת התמונה נכשלה — נסה שוב",
        errorSave:          "השמירה נכשלה — נסה שוב",
      },
    },
    leads: {
      title:               "לידים",
      tabLeads:            "לידים",
      tabTemplates:        "תבניות תגובה",
      searchPlaceholder:   "חיפוש לפי שם, חברה, תפקיד…",
      noLeads:             "אין לידים עדיין",
      noLeadsHint:         "השתמש בתוסף LinkedIn כדי להגיב על פוסטים — הלידים יופיעו כאן אוטומטית.",
      noResults:           "אין לידים התואמים לחיפוש",
      clearSearch:         "נקה חיפוש",
      notesPlaceholder:    "הוסף הערה…",
      saveNotes:           "שמור",
      deleteLead:          "הסר",
      confirmDelete:       "להסיר ליד זה?",
      viewProfile:         "צפה בלינקדאין",
      usedTemplate:        "תבנית ששימשה",
      addedOn:             "נוסף",
      noTemplates:         "אין תבניות עדיין",
      noTemplatesHint:     "הוסף את תבנית התגובה הראשונה שלך למטה.",
      newTemplate:         "+ תבנית חדשה",
      templateTitle:       "שם התבנית",
      templateTitlePlaceholder: "לדוגמה: פתיחה כללית",
      templateBody:        "טקסט התגובה",
      templateBodyPlaceholder:  "כתוב את התגובה שיעקב ידביק…",
      templateImage:       "תמונה (אופציונלי)",
      chooseImage:         "בחר מהגלריה",
      noImageSelected:     "ללא תמונה",
      removeImage:         "הסר",
      saveTemplate:        "שמור תבנית",
      saving:              "שומר…",
      cancel:              "ביטול",
      editTemplate:        "ערוך",
      deleteTemplate:      "מחק",
      confirmDeleteTemplate: "למחוק תבנית זו?",
    },
    modal: {
      newPosition:  "משרה חדשה",
      howToAdd:     "איך תרצה להוסיף?",
      pasteEmail:   "הדבק את מייל המשרה",
      reviewSave:   "סקירה ושמירה",
      pasteTitle:   "הדבק ממייל",
      pasteSub:     "העתק והדבק מייל משרה — נמלא את השדות אוטומטית",
      manualTitle:  "מילוי ידני",
      manualSub:    "הזן את פרטי המשרה בעצמך",
      emailPlaceholder: "הדבק כאן את המייל המלא — נושא, גוף, כל מה שיש. ככל שיש יותר פרטים כך ייטב.",
      parseError:   "לא הצלחנו לקרוא את המייל. נסה שוב או מלא את השדות ידנית.",
      back:         "חזור →",
      skipManual:   "דלג, מלא ידנית",
      extract:      "← חלץ פרטים",
      reading:      "קורא מייל…",
      jobTitle:     "כותרת המשרה",
      jobTitlePlaceholder: "מהנדס תוכנה בכיר",
      client:       "לקוח",
      clientHint:   "עבור מי אתה מגייס?",
      clientPlaceholder: "חברת ABC",
      location:     "מיקום",
      salaryRange:  "טווח שכר",
      description:  "תיאור המשרה",
      descriptionPlaceholder: "תאר את התפקיד, האחריות, תרבות החברה…",
      requirements: "דרישות",
      requirementsPlaceholder: "כישורים, ניסיון, כישורים נדרשים…",
      requiredError: "כותרת המשרה ושם הלקוח הם שדות חובה.",
      saveError:    "משהו השתבש. אנא נסה שוב.",
      createPosition: "צור משרה",
      saving:       "שומר…",
    },
    candidates: {
      title:          "מועמדים",
      searchPlaceholder: "חיפוש לפי שם, כישור, תפקיד, מיקום…",
      uploadBtn:      "העלה קו\"ח",
      dropzone:       "גרור קו\"ח לכאן או לחץ להעלאה",
      dropzoneSub:    "PDF או Word · קובץ אחד או יותר",
      processing:     "מעבד…",
      parsed:         "עובד",
      matched: (n: number) => `הותאם ל-${n} ${n !== 1 ? "משרות" : "משרה"}`,
      failedParse:    "לא ניתן לנתח",
      alreadyExists:  "כבר במאגר",
      emptyTitle:     "אין מועמדים עדיין",
      emptySubtitle:  "העלה קו\"ח כדי לבנות את מאגר הכישרונות. המערכת תתאים אותם למשרות פתוחות אוטומטית.",
      noResults:      "אין מועמדים התואמים לחיפוש",
      clearSearch:    "נקה חיפוש",
      sourceLabels:   { jobmaster: "ג'ובמאסטר", manual: "ידני", website: "אתר" } as Record<string, string>,
      yrsExp: (n: number) => `${n} שנ${n !== 1 ? "ים" : "ה"}`,
      back:           "כל המועמדים →",
      contact:        "פרטי קשר",
      experience:     "ניסיון",
      skills:         "כישורים",
      industries:     "תעשיות",
      summary:        "סיכום",
      matchedRoles:   "תפקידים מותאמים",
      noMatches:      "אין התאמות למשרות עדיין",
      downloadCV:     "הורד קו\"ח",
      updatedAt:      "עודכן לאחרונה",
    },
    emailInbox: {
      title:                "תיבת דואר",
      subtitle:             "מחובר לתיבת Gmail — סריקה אוטומטית כל 15 דקות. קו\"ח מקושרים למשרות ומותאמים אוטומטית.",
      checking:             "בודק חיבור…",
      connected:            "מחובר ל-Gmail",
      connectFirst:         "יש לשמור פרטי Gmail לפני הסריקה.",
      settingsTitle:        "הגדרות Gmail IMAP",
      labelEmail:           "כתובת Gmail",
      labelAppPassword:     "סיסמת אפליקציה",
      appPasswordPlaceholder: "xxxx xxxx xxxx xxxx",
      appPasswordHint:      "צור סיסמת אפליקציה בחשבון Google → אבטחה → אימות דו-שלבי.",
      saveBtn:              "שמור",
      saving:               "שומר…",
      cancel:               "ביטול",
      changeSettings:       "שנה הגדרות",
      pollTitle:            "סריקת תיבת דואר",
      pollBtn:              "סרוק עכשיו",
      polling:              "סורק…",
      resultScanned:        (n: number) => `${n} הודעות נסרקו`,
      resultImported:       (n: number) => `${n} קו"ח יובאו`,
      resultErrors:         "שגיאות:",
      lastPolled:           "סריקה אחרונה:",
      never:                "לא נסרק עדיין",
      appliedBadge:         "מועמד פעיל",
      autoSyncActive:       "סנכרון אוטומטי פעיל",
      autoSyncInterval:     "סורק את תיבת הדואר כל 15 דקות",
      autoSyncNext:         (n: number) => `סריקה הבאה בעוד ${n} דקות`,
      autoSyncSoon:         "סורק בקרוב…",
      updateTitle:          "עדכון אפליקציה",
      updateVersion:        "גרסה",
      updateCommit:         "בנייה",
      updateLastUpdated:    "עודכן לאחרונה",
      updateBtn:            "עדכן עכשיו",
      updating:             "מתחיל עדכון…",
      updateStarted:        "העדכון החל — האפליקציה תופעל מחדש תוך כ-2 דקות. פתח מחדש את הדף לאחר מכן.",
      updateError:          "שגיאה בהפעלת העדכון",
    },
  },
} as const;

export type T = (typeof translations)["en"];
export default translations;
