export const translations = {
  en: {
    sidebar: {
      recruiterDesk: "Recruiter Desk",
      positions:  "Positions",
      customers:  "Customers",
      candidates: "Candidates",
      linkedin:   "LinkedIn",
      greetings: ["Good morning", "Good afternoon", "Good evening"],
      tagline:   "Connecting Talent.\nPowering Futures.",
    },
    positions: {
      title:       "Positions",
      newPosition: "+ New Position",
      subtitle: (o: number, f: number) =>
        `${o} open · ${f} filled`,
      metrics: {
        open:      "Open",
        filled:    "Filled",
        cancelled: "Cancelled",
        toReview:  "To Review",
      },
      statusLabel: {
        open:      "Open",
        filled:    "Filled",
        cancelled: "Cancelled",
      },
      emptyTitle:    "No positions yet",
      emptySubtitle: "Add your first open role to start building your candidate pipeline.",
      emptyCta:      "+ New Position",
      filteredEmpty: "No positions match this filter",
      clearFilter:   "Clear filter",
      searchPlaceholder: "Search by title or client…",
      noSearchResults:   "No positions match your search",
      clearSearch:       "Clear search",
      noCandidates:  "No candidates",
      matched:       "matched",
      pipeline: {
        inPool:       "In Pool",
        clientReview: "Client Review",
        interview:    "Interview",
        hired:        "Hired",
      },
    },
    detail: {
      back:         "← All Positions",
      location:     "Location",
      salary:       "Salary",
      created:      "Created",
      addLocation:  "Add location",
      addSalary:    "Add salary range",
      today:        "Today",
      yesterday:    "Yesterday",
      daysAgo: (n: number) => `${n} days ago`,
      publishJob:   "Publish Job",
      inPool: (n: number) => `${n} candidate${n !== 1 ? "s" : ""} in pool`,
      statusLabel: {
        open:      "Open",
        filled:    "Filled",
        cancelled: "Cancelled",
      },
      aboutJob:        "About the job",
      addDescription:  "+ Add job description",
      requirements:    "Requirements",
      addRequirements: "+ Add requirements",
      edit:   "✏ Edit",
      save:   "Save",
      cancel: "Cancel",
      candidates:      "Candidates",
      matched:         "matched",
      noCandidatesYet: "No candidates matched yet",
      showWeak: (n: number) => `▼ Show ${n} weak match${n !== 1 ? "es" : ""}`,
      hideWeak: (n: number) => `▲ Hide ${n} weak match${n !== 1 ? "es" : ""}`,
      rejected: (n: number) => `${n} candidate${n !== 1 ? "s" : ""} rejected`,
      moveToStage: "Move to stage",
      reject:      "Reject",
      pendingSection:      "To Review",
      reviewedSection:    "Relevant",
      notRelevantSection: "Not Relevant",
      markRelevant:    "Relevant",
      markNotRelevant: "Not Relevant",
      showNotRelevant: (n: number) => `▼ Show ${n} not relevant`,
      hideNotRelevant: (n: number) => `▲ Hide ${n} not relevant`,
      candidateStatus: {
        open:          "In Pool",
        client_review: "Client Review",
        interview:     "Interview",
        hired:         "Hired",
        rejected:      "Rejected",
        relevant:      "Relevant",
        not_relevant:  "Not Relevant",
      },
      strengthLabel: {
        strong:   "Strong Match",
        possible: "Possible Match",
        weak:     "Weak Match",
      },
      whyFit:       "Why they fit",
      copy:         "Copy",
      copied:       "Copied!",
      viewProfile:  "View full profile",
      experience:   "Experience",
      yrsExp: (n: number) => `${n} yr${n !== 1 ? "s" : ""}`,
      skills:       "Skills",
      summary:      "Summary",
      contact:      "Contact",
      removePositionOption:   "Remove position",
      removePositionTitle:    "Remove position?",
      removePositionBody:     (title: string) => `This will permanently delete "${title}" and all its candidate matches. This cannot be undone.`,
      removePositionConfirm:  "Yes, remove",
    },
    candidates: {
      title:          "Candidates",
      searchPlaceholder: "Search by name, skill, title, location…",
      uploadBtn:      "Upload CV",
      dropzone:       "Drop CVs here or click to upload",
      dropzoneSub:    "PDF or Word · one or many at once",
      processing:     "Processing…",
      parsed:         "Parsed",
      matched: (n: number) => `Matched to ${n} position${n !== 1 ? "s" : ""}`,
      failedParse:    "Could not parse",
      emptyTitle:     "No candidates yet",
      emptySubtitle:  "Upload CVs to build your talent pool. The system will match them to open positions automatically.",
      noResults:      "No candidates match your search",
      clearSearch:    "Clear search",
      sourceLabels:   { jobmaster: "JobMaster", linkedin: "LinkedIn", manual: "Manual" } as Record<string, string>,
      yrsExp: (n: number) => `${n} yr${n !== 1 ? "s" : ""}`,
      back:           "← All Candidates",
      contact:        "Contact",
      experience:     "Experience",
      skills:         "Skills",
      industries:     "Industries",
      summary:        "Summary",
      matchedRoles:   "Matched Roles",
      noMatches:      "No position matches yet",
      downloadCV:     "Download CV",
    },
    customers: {
      title:         "Customers",
      addClient:     "+ Add Client",
      totalClients:  "Total Clients",
      active:        "Active",
      totalContacts: "Total Contacts",
      openPositions: "Open Positions",
      contacts:      "Contacts",
      addContact:    "+ Add Contact",
      emptyTitle:    "No clients yet",
      emptySubtitle: "Add your first client to start building your customer directory.",
      emptyCta:      "+ Add Client",
      back:          "← All Customers",
      edit:          "✏ Edit",
      save:          "Save",
      cancel:        "Cancel",
      industry:      "Industry",
      website:       "Website",
      linkedin:      "LinkedIn",
      noPositions:   "No open positions linked to this client.",
      noContacts:    "No contacts yet.",
      deleteContact:  "Remove",
      confirmDelete:  "Remove this contact?",
      candidateCount: (n: number) => `${n} candidate${n !== 1 ? "s" : ""}`,
      removeClientOption:  "Remove client",
      removeClientTitle:   "Remove client?",
      removeClientBody:    (name: string) => `This will permanently delete "${name}" and all associated data. This cannot be undone.`,
      removeClientConfirm: "Yes, remove",
      // Add Client modal
      addClientTitle:         "Add Client",
      step1Title:             "LinkedIn Company URL",
      linkedinUrlLabel:       "LinkedIn Company URL",
      linkedinUrlPlaceholder: "https://www.linkedin.com/company/…",
      fetchBtn:               "Fetch",
      fetching:               "Fetching…",
      fetchError:             "Couldn't fetch company data. Check the URL and try again.",
      fillManually:           "Fill in manually",
      step2Title:             "Review & Save",
      companyName:            "Company Name",
      tagline:                "Tagline",
      saveClient:             "Save Client",
      saving:                 "Saving…",
      // Add Contact modal
      addContactTitle: "Add Contact",
      contactName:     "Name",
      contactTitle:    "Title",
      contactEmail:    "Email",
      contactPhone:    "Phone",
      saveContact:     "Save Contact",
      // Position modal dropdown
      clientDropdownPlaceholder: "Search clients…",
      createNewClient:           "+ Create new client",
    },
    modal: {
      newPosition:  "New Position",
      howToAdd:     "How would you like to add it?",
      pasteEmail:   "Paste the job email",
      reviewSave:   "Review & Save",
      pasteTitle:   "Paste from email",
      pasteSub:     "Copy & paste a job email — we'll fill in the fields automatically",
      manualTitle:  "Fill in manually",
      manualSub:    "Type in the job details yourself",
      emailPlaceholder: "Paste the full email here — subject, body, anything you have. The more detail, the better.",
      parseError:   "Couldn't read the email. Try again or fill in the fields manually.",
      back:         "← Back",
      skipManual:   "Skip, fill manually",
      extract:      "Extract details →",
      reading:      "Reading email…",
      jobTitle:     "Job Title",
      jobTitlePlaceholder: "Senior Software Engineer",
      client:       "Client",
      clientHint:   "Who are you recruiting for?",
      clientPlaceholder: "Acme Corp",
      location:     "Location",
      salaryRange:  "Salary Range",
      description:  "Job Description",
      descriptionPlaceholder: "Describe the role, responsibilities, company culture…",
      requirements: "Requirements",
      requirementsPlaceholder: "Skills, experience, qualifications needed…",
      requiredError: "Job title and client name are required.",
      saveError:    "Something went wrong. Please try again.",
      createPosition: "Create Position",
      saving:       "Saving…",
    },
  },

  he: {
    sidebar: {
      recruiterDesk: "מערכת גיוס",
      positions:  "משרות",
      customers:  "לקוחות",
      candidates: "מועמדים",
      linkedin:   "לינקדאין",
      greetings: ["בוקר טוב", "צהריים טובים", "ערב טוב"],
      tagline:   "מחברים כישרונות.\nמניעים עתידות.",
    },
    positions: {
      title:       "משרות",
      newPosition: "+ משרה חדשה",
      subtitle: (o: number, f: number) =>
        `${o} פתוחות · ${f} אוישו`,
      metrics: {
        open:      "פתוחות",
        filled:    "אוישו",
        cancelled: "בוטלו",
        toReview:  "לסקירה",
      },
      statusLabel: {
        open:      "פתוחה",
        filled:    "אוישה",
        cancelled: "בוטלה",
      },
      emptyTitle:    "אין משרות עדיין",
      emptySubtitle: "הוסף את המשרה הראשונה שלך כדי להתחיל לבנות את צינור המועמדים.",
      emptyCta:      "+ משרה חדשה",
      filteredEmpty: "אין משרות התואמות לסינון זה",
      clearFilter:   "נקה סינון",
      searchPlaceholder: "חיפוש לפי תפקיד או לקוח…",
      noSearchResults:   "אין משרות התואמות לחיפוש",
      clearSearch:       "נקה חיפוש",
      noCandidates:  "אין מועמדים",
      matched:       "הותאמו",
      pipeline: {
        inPool:       "בסל",
        clientReview: "בדיקת לקוח",
        interview:    "ראיון",
        hired:        "גויס",
      },
    },
    detail: {
      back:        "כל המשרות →",
      location:    "מיקום",
      salary:      "שכר",
      created:     "נוצרה",
      addLocation: "הוסף מיקום",
      addSalary:   "הוסף טווח שכר",
      today:       "היום",
      yesterday:   "אתמול",
      daysAgo: (n: number) => `לפני ${n} ימים`,
      publishJob:  "פרסם משרה",
      inPool: (n: number) => `${n} מועמד${n !== 1 ? "ים" : ""} בסל`,
      statusLabel: {
        open:      "פתוחה",
        filled:    "אוישה",
        cancelled: "בוטלה",
      },
      aboutJob:        "אודות המשרה",
      addDescription:  "+ הוסף תיאור משרה",
      requirements:    "דרישות",
      addRequirements: "+ הוסף דרישות",
      edit:   "✏ עריכה",
      save:   "שמור",
      cancel: "ביטול",
      candidates:      "מועמדים",
      matched:         "הותאמו",
      noCandidatesYet: "לא הותאמו מועמדים עדיין",
      showWeak: (n: number) => `▼ הצג ${n} התאמה${n !== 1 ? "ות" : ""} חלשה`,
      hideWeak: (n: number) => `▲ הסתר ${n} התאמה${n !== 1 ? "ות" : ""} חלשה`,
      rejected: (n: number) => `${n} מועמד${n !== 1 ? "ים" : ""} נדחו`,
      moveToStage: "העבר לשלב",
      reject:      "דחה",
      pendingSection:      "לסקירה",
      reviewedSection:    "רלוונטי",
      notRelevantSection: "לא רלוונטי",
      markRelevant:    "רלוונטי",
      markNotRelevant: "לא רלוונטי",
      showNotRelevant: (n: number) => `▼ הצג ${n} לא רלוונטי${n !== 1 ? "ם" : ""}`,
      hideNotRelevant: (n: number) => `▲ הסתר ${n} לא רלוונטי${n !== 1 ? "ם" : ""}`,
      candidateStatus: {
        open:          "מאגר",
        client_review: "בדיקת לקוח",
        interview:     "ראיון",
        hired:         "גויס",
        rejected:      "נדחה",
        relevant:      "רלוונטי",
        not_relevant:  "לא רלוונטי",
      },
      strengthLabel: {
        strong:   "התאמה חזקה",
        possible: "התאמה אפשרית",
        weak:     "התאמה חלשה",
      },
      whyFit:       "למה הם מתאימים",
      copy:         "העתק",
      copied:       "הועתק!",
      viewProfile:  "לפרופיל המלא",
      experience:   "ניסיון",
      yrsExp: (n: number) => `${n} שנ${n !== 1 ? "ים" : "ה"}`,
      skills:       "כישורים",
      summary:      "סיכום",
      contact:      "פרטי קשר",
      removePositionOption:   "הסר משרה",
      removePositionTitle:    "הסר משרה?",
      removePositionBody:     (title: string) => `פעולה זו תמחק לצמיתות את "${title}" ואת כל התאמות המועמדים שלה. לא ניתן לבטל פעולה זו.`,
      removePositionConfirm:  "כן, הסר",
    },
    customers: {
      title:         "לקוחות",
      addClient:     "+ הוסף לקוח",
      totalClients:  "סה\"כ לקוחות",
      active:        "פעילים",
      totalContacts: "סה\"כ אנשי קשר",
      openPositions: "משרות פתוחות",
      contacts:      "אנשי קשר",
      addContact:    "+ הוסף איש קשר",
      emptyTitle:    "אין לקוחות עדיין",
      emptySubtitle: "הוסף את הלקוח הראשון שלך כדי להתחיל לבנות את ספריית הלקוחות.",
      emptyCta:      "+ הוסף לקוח",
      back:          "כל הלקוחות →",
      edit:          "✏ עריכה",
      save:          "שמור",
      cancel:        "ביטול",
      industry:      "תעשייה",
      website:       "אתר",
      linkedin:      "לינקדאין",
      noPositions:   "אין משרות פתוחות המקושרות ללקוח זה.",
      noContacts:    "אין אנשי קשר עדיין.",
      deleteContact:  "הסר",
      confirmDelete:  "להסיר איש קשר זה?",
      candidateCount: (n: number) => `${n} מועמד${n !== 1 ? "ים" : ""}`,
      removeClientOption:  "הסר לקוח",
      removeClientTitle:   "הסר לקוח?",
      removeClientBody:    (name: string) => `פעולה זו תמחק לצמיתות את "${name}" וכל הנתונים הקשורים. לא ניתן לבטל פעולה זו.`,
      removeClientConfirm: "כן, הסר",
      addClientTitle:         "הוסף לקוח",
      step1Title:             "כתובת LinkedIn של החברה",
      linkedinUrlLabel:       "כתובת LinkedIn",
      linkedinUrlPlaceholder: "https://www.linkedin.com/company/…",
      fetchBtn:               "שלוף",
      fetching:               "שולף…",
      fetchError:             "לא הצלחנו לשלוף נתוני חברה. בדוק את הכתובת ונסה שוב.",
      fillManually:           "מלא ידנית",
      step2Title:             "סקירה ושמירה",
      companyName:            "שם החברה",
      tagline:                "תיאור קצר",
      saveClient:             "שמור לקוח",
      saving:                 "שומר…",
      addContactTitle: "הוסף איש קשר",
      contactName:     "שם",
      contactTitle:    "תפקיד",
      contactEmail:    "אימייל",
      contactPhone:    "טלפון",
      saveContact:     "שמור איש קשר",
      clientDropdownPlaceholder: "חפש לקוחות…",
      createNewClient:           "+ צור לקוח חדש",
    },
    modal: {
      newPosition:  "משרה חדשה",
      howToAdd:     "איך תרצה להוסיף?",
      pasteEmail:   "הדבק את מייל המשרה",
      reviewSave:   "סקירה ושמירה",
      pasteTitle:   "הדבק ממייל",
      pasteSub:     "העתק והדבק מייל משרה — נמלא את השדות אוטומטית",
      manualTitle:  "מילוי ידני",
      manualSub:    "הזן את פרטי המשרה בעצמך",
      emailPlaceholder: "הדבק כאן את המייל המלא — נושא, גוף, כל מה שיש. ככל שיש יותר פרטים כך ייטב.",
      parseError:   "לא הצלחנו לקרוא את המייל. נסה שוב או מלא את השדות ידנית.",
      back:         "חזור →",
      skipManual:   "דלג, מלא ידנית",
      extract:      "← חלץ פרטים",
      reading:      "קורא מייל…",
      jobTitle:     "כותרת המשרה",
      jobTitlePlaceholder: "מהנדס תוכנה בכיר",
      client:       "לקוח",
      clientHint:   "עבור מי אתה מגייס?",
      clientPlaceholder: "חברת ABC",
      location:     "מיקום",
      salaryRange:  "טווח שכר",
      description:  "תיאור המשרה",
      descriptionPlaceholder: "תאר את התפקיד, האחריות, תרבות החברה…",
      requirements: "דרישות",
      requirementsPlaceholder: "כישורים, ניסיון, כישורים נדרשים…",
      requiredError: "כותרת המשרה ושם הלקוח הם שדות חובה.",
      saveError:    "משהו השתבש. אנא נסה שוב.",
      createPosition: "צור משרה",
      saving:       "שומר…",
    },
    candidates: {
      title:          "מועמדים",
      searchPlaceholder: "חיפוש לפי שם, כישור, תפקיד, מיקום…",
      uploadBtn:      "העלה קו\"ח",
      dropzone:       "גרור קו\"ח לכאן או לחץ להעלאה",
      dropzoneSub:    "PDF או Word · קובץ אחד או יותר",
      processing:     "מעבד…",
      parsed:         "עובד",
      matched: (n: number) => `הותאם ל-${n} ${n !== 1 ? "משרות" : "משרה"}`,
      failedParse:    "לא ניתן לנתח",
      emptyTitle:     "אין מועמדים עדיין",
      emptySubtitle:  "העלה קו\"ח כדי לבנות את מאגר הכישרונות. המערכת תתאים אותם למשרות פתוחות אוטומטית.",
      noResults:      "אין מועמדים התואמים לחיפוש",
      clearSearch:    "נקה חיפוש",
      sourceLabels:   { jobmaster: "ג'ובמאסטר", linkedin: "לינקדאין", manual: "ידני" } as Record<string, string>,
      yrsExp: (n: number) => `${n} שנ${n !== 1 ? "ים" : "ה"}`,
      back:           "כל המועמדים →",
      contact:        "פרטי קשר",
      experience:     "ניסיון",
      skills:         "כישורים",
      industries:     "תעשיות",
      summary:        "סיכום",
      matchedRoles:   "תפקידים מותאמים",
      noMatches:      "אין התאמות למשרות עדיין",
      downloadCV:     "הורד קו\"ח",
    },
  },
} as const;

export type T = (typeof translations)["en"];
export default translations;
